services:
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - ./mariadb:/var/lib/mysql:Z
    ports:
      - 3306:3306
    restart: unless-stopped
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=${MARIADB_SERVER}
    ports:
      - 8080:80
    depends_on:
      - mariadb
  clientemqtt:
    image: clientemqtt
    build:
      context: ./clienteMqtt
    container_name: clientemqtt
    environment:
      - TZ=America/Argentina/Buenos_Aires 
      - SERVIDOR=${SERVIDOR} #Se reemplazará por la env var SERVIDOR definida en .env
      - TOPICO=${TOPICO}
      - MARIADB_SERVER=${MARIADB_SERVER}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_USER_PASS=${MARIADB_USER_PASS}
      - MARIADB_DB=${MARIADB_DB}
    restart: unless-stopped
    depends_on:
      - mariadb
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    user: "1000:1000"
    ports:
      - 1883:1883
      - 8883:8883
    restart: unless-stopped
    volumes:
      - ~/docker/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ~/docker/mosquitto/config:/mosquitto/config